version: "3.7"

services:
  fakelog:
    container_name: fakelog
    build:
      context: fakelog/
      dockerfile: Dockerfile

  rsyslog:
    container_name: rsyslog
    build:
      context: rsyslog/
      dockerfile: Dockerfile
    ports:
      - 9090:10514
    
  redis:
    container_name: redis
    build:
      context: redis/
      dockerfile: Dockerfile
    ports:
      - 6379:6379

  fastapi:
    container_name: fastapi
    build:
      context: fastapi/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
